### ISSUE TITLE
Feedback needed in a real smartboard plugged - Se necesita colaboración para probar con una pizarra smartboard real

### ISSUE THREAD

**Issue by aosucas499** [aosucas499/smartdre#1]

**Comment by cwalker** [comment]
Hi! I have a SMART Podium 422w.
Everything works fine, but need to calibrate the screen and save docker conainer:

#docker exec -i -t smartboard bash
#/opt/SMART\ Technologies/SMART\ Product\ Drivers/bin/Orient
#exit
#docker container commit smartboard aosucas499/smartdre

Possible hide Floating Tools Toolbar? It is not active for me

**Comment by aosucas499** [comment]
Hi thank you for reply and feedback.

I have build a new brach with user in the container and shared folder. Download and try:

`cd ~`
`git clone https://github.com/aosucas499/smartdre.git`
`cd smartdre`
`./install-smartdre`
`./smartdre`

To orient, try in a terminal when the container is running:

`cd ~/smartdre`

`chmod +x  orient`
`./orient `

or

`docker exec -it smartboard bash /opt/SMART\ Technologies/SMART\ Product\ Drivers/bin/Orient`


Now that the container have a shared folder you could hide floating tools in the system tray icon, right button, hide floating tools and that this settings keep.

Try and give me feedback. Thank you.

**Comment by cwalker** [comment]
Hello! I apologize for not writing for a long time.
I checked the latest version and it doesn't work for me.

The last working version was from 11/25/2020
Old version:
![Screenshot from 2020-12-02 10-19-30](https://user-images.githubusercontent.com/1335913/100838338-acda0580-348b-11eb-932e-4b8ac056f377.png)
New version:
![Screenshot from 2020-12-02 10-43-28](https://user-images.githubusercontent.com/1335913/100838361-b5cad700-348b-11eb-8dad-3ffd78a020a4.png)
Strange double device. May be conflict?

**Comment by aosucas499** [comment]
Thanks for the amazing feedback! I have the repo very disorganized trying with different drivers and distributions. I'll work about it and I upload a new one for testing. The problem is that the model I have is the most difficult to get work and I change a lot of things(model sb480). Thanks.

**Comment by aosucas499** [comment]
I have modified the dockers and the app, you can try again and give me feedback. Even you can try different alternatives, executing smardre, smartdre-0.3, smartdre-0.4. Thank you so much.

**Comment by cwalker** [comment]
I checked latest version today.
 smartdre-0.3 version works perfect!

**Comment by aosucas499** [comment]
I'm glad. Thank you so much. Even orientation?

**Comment by cwalker** [comment]
Yes, but edit required ./orient script (change smartdre to smartdre-0.3)
Thank you for great job!

**Comment by aosucas499** [comment]
Great! I'll setting the version 0.3 as main so all work with smartdre and orient. Thank you so much!!
