### ISSUE TITLE
Smart Notebook

### ISSUE THREAD

**Issue by josmarsua** [aosucas499/smartdre#3]
Hola compañero, en primer lugar muchísimas gracias por el trabajo que te estás pegando ya que para muchos de nosotros es de gran utilidad. Quería hacerte una pregunta, ¿sabes cómo instalar la aplicación SmartNotebook en los nuevos sistemas EducaAndOS? Llevo bastante tiempo intentándolo y no consigo dar con la forma. Gracias!

**Comment by aosucas499** [comment]
Hola compañero, en este docker no está incluído el smart notebook porque es muy pesado y me parece un programa que puede ser perfectamente suplido o mejorada con la aplicación openboard. ¿Por qué necesitas el programa SmartNotebook?

**Comment by josmarsua** [comment]
Yo soy también partidario de que se use la aplicación openboard pero algunos compañeros tienen bastantes ficheros creados con SmartNotebook y requieren de esa aplicación para poder abrirlos.

**Comment by aosucas499** [comment]
No sé si te has fijado que la aplicación SmartNotebook deja abrir esos archivos y exportarlos a todos estos [formatos](http://onlinehelp.smarttech.com/english/windows/help/notebook/11_0_0/Content/Product-User/CreatingAndWorkingWithFiles/ExportingFiles.htm). ¿Te valdría la opción de en un equipo instalar Guadalinex Next o Slim y con la app Smartnotebook instalada, que los compañeros pasasen sus archivos a estos formatos? Te digo esto porque creo que es la opción con más futuro, que sigan utilizando una herramienta obsoleta solo va hacer que sigan creando material obsoleto.
