### ISSUE TITLE
hp probook 455 g7 y problema con función táctil smartboard480

### ISSUE THREAD

**Issue by ipg78** [aosucas499/smartdre#4]
Hola, en primer lugar gracias por vuestro trabajo. os escribo porque tengo un problemilla: He seguido el tutorial para instalar el educandos + con el paquete de apps guadalinex 20, he instalado la app de smartboard y hasta ahí todo ok. luego al conectar el portátil a la pizarra y comprobar en la app que está conectada no tengo función táctil y aparentemente está todo correcto. Solamente y curiosamente me ha dejado calibrarla con la app de calibración incluida, pero luego no responde el modo táctil. lo tengo puesto el modo espejo en el hp para duplicar pantalla. no sé si con esa info me podéis ayudar gracias de antemano

**Comment by ipg78** [comment]
instalé la app de la smartboard desde el usuario admin y luego inicie sesión con el usuario/usuario

**Comment by aosucas499** [comment]
Buenas noches, este proyecto es para usar las pizarras en ubuntu o linux mint. Para educaandos hay un instalador en la app-guadalinex-20 como leo que has usado y el proyecto y los problemas se comenta [aquí](https://github.com/aosucas499/guadalinex/issues). Te pongo un tutorial en unos días aquí para que te funcione el táctil. Esta versión va genial pero la de educaandos está siendo depurada y hay que hacer unos pasos para que funcione en cada inicio.

**Comment by ipg78** [comment]
Muchas gracias por responder. Esperaré al tutorial. Saludos.

**Comment by aosucas499** [comment]
[Tutorial](https://docs.google.com/document/d/1TlTJKOP31kkPD9fVH-N06HCu_lQvLSVt3tqolNzbGG0/edit?usp=sharing)

**Comment by ipg78** [comment]
> [Tutorial](https://docs.google.com/document/d/1TlTJKOP31kkPD9fVH-N06HCu_lQvLSVt3tqolNzbGG0/edit?usp=sharing)

Muchas gracias con el tutorial funciona...es un pelín engorroso pero funciona, sobre todo para el profesorado que no tiene competencia digital, pero es una solución. Muchas gracias. 
Lo que estoy pensando es instalar las versiones linux que dicen que soportan perfectamente el tácil en estas pirzarras sin tener que hacer nada, puede ser linux mint esa versión? gracias otra vez.

**Comment by aosucas499** [comment]
Sí, te lo puse en el comentario anterior. Linux mint funciona genial, aunque solo se ha probado en la versión 19.3 que está basada en Ubuntu 18. Si pruebas en esa versión o en la 20 de mint te agradecería me contaras qué tal fue.

[Descargas linux mint](https://linuxmint.com/download_all.php)
